[package]
name = "diffeq-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
eframe = "0.27.2"
egui = "0.27.2"
egui_plot = "0.27.2"
